### ISSUE TITLE
Add configuration to verify and/or require audience claim

### ISSUE THREAD

**Issue by MikeEdgar** [smallrye/smallrye-jwt#110]
Utilizing `JwtConsumerBuilder.setExpectedAudience(Boolean, String...)`. The logic should align with what is currently done to require/validate the issuer claim.

`smallrye.jwt.verify.audiences` (`Optional<Set<String>>`)
`smallrye.jwt.verify.requireaud` (`Optional<Boolean>`)

Potential configurations if incorporated into specification:
`mp.jwt.verify.audiences`
`mp.jwt.verify.requireaud`

*Edit*: make expected audiences property plural to align with JOSE4J API and OpenLiberty implementation.

**Comment by MikeEdgar** [comment]
This change is [ready for a PR (830cdd)](https://github.com/MikeEdgar/smallrye-jwt/commit/830cdd1b0d9572e205c5ac13b41088fcee800cf0), but is based on the changes in #109. I'll wait to submit until I hear feedback on that request first.

**Comment by MikeEdgar** [comment]
I am wondering if the second property `requireaud` would better be implemented using the approach in #80. Thoughts?

**Comment by sberyozkin** [comment]
@MikeEdgar thanks. Yes, I propose to generalize the `smallrye.jwt.verify.requireaud` around the #80 idea. (and have the existing "mp.jwt.verify.requireiss" deprecated too, `iss` can be a default value for the would be new property) 

That said, thinking about it, would it be really be redundant after all, if one requires the verification of the specific audience values, then one already says it is required :-) ? In general, I think that only requiring a given claim is only useful if the user code tries to do something with it, it does not in itself makes the token validation more robust, unless the specific expected values are configured.

Re `smallrye.jwt.verify.audiences` - the documentation for this standard claim (example in the OIDC Core) already says it can be a single value or an array. I'd prefer to have a property which says that a value of the 'aud'(ience) claim is being verified, a non-plural version, in 90% cases the audience is a single value (unless you have some different statistics :-) ? ), we don't have to base the property names on the internal implementation or integration specific configurations. Does it sound reasonable ?

**Comment by MikeEdgar** [comment]
I did a bit more thinking about this one, and I really like the idea of a generic approach to required/formatting of claims. I added a comment to eclipse/microprofile-jwt-auth#121 regarding that based on some discussion on the MP mailing list.

I added [this commit](https://github.com/MikeEdgar/smallrye-jwt/commit/5c4c9d60b782651086e5419cb612a1ecded1014f) which includes two general validators, one for required claims and one for validation of the pattern. I believe using a pattern resolves the question of singular vs. plural and single vs. array claims. The pattern matching validation may need to be relaxed to require at least one match if multiple are present.

Note that commit also includes some consolidation of default values to the injection points rather than specifying them in multiple locations, some of which conflicted (e.g. `requireNamedPrincipal`). There may be some impact to Thorntail there and I'm happy to do a PR to account for it if you're on board with the changes.

**Comment by sberyozkin** [comment]
@MikeEdgar I'm sorry, these changes are covering so many things beyond the original requirement that I'm finding it difficult to understand what is going on. I prefer applying primitive changes given the overall sensitivity of the code. Besides I'd like to avoid Jose4J leaking via JWTContextInfo, it took me awhile to move it out of it earlier when I was doing a Thorntail MP JWT + Keycloak integration. 
Lets take a step back. This issue is about verifying the value of the audience claim - lets focus only on this issue here and do a basic string comparison inside the parser code. If you'd like, do initialize a single error code validator with either the iss or aud constraints, but lets avoid the regex, how many endpoints out there need to support N audience or iss values such that simply listing say 2 audience values is not enough ? And the audience is really a precise comparison thing from the security point of view, the regex can be too loose and allow the unexpected audiences for ex.  

And I'd still prefer the property have a non-plural form.

Thanks for your effort, it is a quality one as usual :-), but lets stay conservative and apply the changes slower.

**Comment by MikeEdgar** [comment]
@sberyozkin, I am good with using a simple string comparison rather than regex/pattern. I was inspired by [David Blevin's 5/31/18 response regarding the `requireiss` option](https://groups.google.com/d/msg/microprofile/IVDoXw12qXo/sbv_nd4yAQAJ), which is what led to my comment in eclipse/microprofile-jwt-auth#121. 

From a naming perspective, I really think the property names should be as flexible and forward-looking as possible, to his point. I.e. use `aud` (or whatever the claim in the JWT is called) in the property rather than an expanded name like `audience` or `audiences`. Thoughts?

I do still want to make the case for using a collection for the audience claim. The reason is that interfaces dealing with `aud` return either a `Set<String>` or a `List<String>` and I think it makes sense to support that. See `JsonWebToken` itself, `org.jose4j.jwt.JwtClaims.getAudience()`, and the logic in `org.jose4j.jwt.consumer.AudValidator`.

It would be very useful to have a generalized approach to validating claims (both their requirement and values - maybe even allowable types), but I can appreciate not wanting to do too much at once. Are you open to such a general approach, provided that it does not rely on Jose4J APIs as the version I linked does?

**Comment by sberyozkin** [comment]
@MikeEdgar are you proposing to have a `smallrye.jwt.verify.aud` property ? Definitely OK with me, not sure why Mp JWT introduced `smallrye.jwt.verify.issuer` instead of ``smallrye.jwt.verify.iss`. We do follow the actual claim name in the property pattern for the default or custom path claims.

I'm not sure I understand what you suggest in the 3rd paragraph ? Do you mean either a single value or collection has to be checked as far as checking the `aud` claim value is concerned ?

Re the generalization, first I think we agree the fix for #80 will provide a simple approach for enforcing that a given set of claims is available in the token, all we want to check at the smallrye-jwt level is that these claims are available.

As far as checking the specific claim values is concerned. I'm not sure how far should we go, we need to ensure the users can offload some work to the smallrye-jwt, but ultimately, only the user code (may be at the matching request filter) can most reliably check if a given claim value is good. especially if its value a JSONObject, not just string or array of strings.
 
The claim values which are quite low level, like `aud`, `iss` - which are mainly relevant for ensuring the token came from the expected origin or is intended for this endpoint, not that useful at the user level code, these are worth checking at the smallrye-jwt, but I don't think we are there just yet to start turning smallrye-jwt into a complete generic claim value validator.

My proposal is to from updateing JWTContextInfo to pass around a list of acceptable audiences, and do a exact string comparison.
Perhaps after this PR is done, if we have one extra requirement to validate at the smallrye-jwt level, we can open an issue and review the options, for example, may be we can pass a Map of claim names to Set of possible values - with the restriction that it can only work for the `simple` claims whose values are not Json objects (i.e, maps). And deprecate JWtContextInfo properties for passing the issuer and aud values since it will be passed in this new map.
Hope you can agree we can approach it iteratively

**Comment by MikeEdgar** [comment]
> are you proposing to have a `smallrye.jwt.verify.aud` property ?

Yes

> Do you mean either a single value or collection has to be checked as far as checking the aud claim value is concerned ?

Yes - either are possible in the JWT so I think the validation should support that. As far as the _acceptable_ values, I am OK with that being a single value. Applications needing more could always validate multiple values outside of smallrye-jwt.

I am also in complete agreement regarding the validation of complex claims. I think anything this library validates would best be limited to primitive claim values.

**Comment by sberyozkin** [comment]
Hi @MikeEdgar 

I mean, please pass around List of Strings for the `aud` claim in the JWTContentInfo, that is fine :-), if we do the `aud` validation in smallrye-jwt then you are right, it has to be complete, I don't think I saw often, if ever, more than 1 audience value, but, well, we will be ready for it :-); when I was referring the the non-plural form I only was talking about the property name, but we have settled on the `smallrye.jwt.verify.aud`. You probably just need to copy & paste the similar configuration for the the `whitelist`, as far as the `aud` constraints are concerned

I was also thinking a bit more about the generic validation, and you approach of passing the error code validators around would actually work for the complex claims as well, but then thought, well, it won't make the life easier for the users if they want to validate say a custom `jwk` claim - they would need to directly depend on Jose4j and ship the custom error validator - or they can jusyt validate it implicitly while processing the complex claim in their code which they will do anyway. So I'm satisfied now that smallrye-jwt will do fine for now with the `iss` and `aud` checks only and indeed we can generalize it later for all the simple claims.
Thanks
