### ISSUE TITLE
Provide a simple JWT generation utility code

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#137]

**Comment by FroMage** [comment]
It would be nice if we could have an API as easy to use as Vert.x (https://vertx.io/docs/apidocs/io/vertx/ext/auth/jwt/JWTAuth.html#generateToken-io.vertx.core.json.JsonObject-io.vertx.ext.jwt.JWTOptions- and https://vertx.io/docs/vertx-auth-jwt/java/#_loading_keys)

```java
	        String jwtToken = jwt.generateToken(
	        		new JsonObject()
	        		.put("username", username)
	        		.put("permissions", permissions),
	                new JWTOptions()
	                  .setSubject("Wiki API")
	                  .setIssuer("Vert.x"));
```

Since we already have the `mp.jwt.verify.publickey[.location]` configuration, we should add a similar config setting for the private key, so we don't have to specify it when generating the token.

**Comment by FroMage** [comment]
Ping @sberyozkin we really need this :)

**Comment by gastaldi** [comment]
Could https://github.com/AdamBien/jwtenizr help here?

**Comment by sebastienblanc** [comment]
@gastaldi Well it could a source of inspiration, it can not be used as it since it's really an utility tool running as an executable jar. The other source of inspiration could be  https://github.com/quarkusio/quarkus-quickstarts/blob/development/security-jwt-quickstart/src/test/java/org/acme/jwt/TokenUtils.java

**Comment by sberyozkin** [comment]
@FroMage @gastaldi @sebastienblanc I will look into it shortly. It has to be done carefully as we can then try to move it into MP JWT. Stay tuned, and thanks for your patience

**Comment by sberyozkin** [comment]
I'll get in some utility code for the next release and worry about a spec-ready builder API later

**Comment by sberyozkin** [comment]
Have been a bit swamped elsewhere but this effort is a priority for me

**Comment by sberyozkin** [comment]
PR is here: #153

**Comment by sberyozkin** [comment]
Another iteration round:\
https://github.com/smallrye/smallrye-jwt/pull/158
