### ISSUE TITLE
Setting default enum values requires using  the underscore

### ISSUE THREAD

**Issue by sberyozkin** [smallrye/smallrye-jwt#399]
@radcortez Hi Roberto, I've been wondering if it is a `smallrye-config` issue.

So, for example, if I set a decryption algorithm property to `RSA-OAEP` then it does not work, I have to use `RSA_OAEP`. This was actually reported by a Quarkus user.
But in Quarkus itself, if I set some enum property as for example `id-token` then it would match the enum `ID_TOKEN`.

I guess `Quarkus` ships a converter which takes care of it - if it is indeed the case - then should this converter be shipped with `smallrye-config` instead ?

**Comment by radcortez** [comment]
Hum, If I remember correctly, in the case of enum we just try to call the enum `valueOf`, so the exact value should work. Let me have a look.

**Comment by radcortez** [comment]
Ah, you are right. Forgot you can't really use `-` in the static enum name :D

In SR Config, we do an exact match, so we cannot even match a value like `RSA-OAEP`, because is not a valid enum. Quarkus adds a specific converter to handle these cases: https://github.com/quarkusio/quarkus/blob/c76ecfc0bb34112de0c7c6e3737056dc843e4b17/core/runtime/src/main/java/io/quarkus/runtime/configuration/HyphenateEnumConverter.java

I'll add it to SR Config as well.

**Comment by sberyozkin** [comment]
@radcortez sounds good, thanks
