### ISSUE TITLE
DefaultJWTTokenParser requires issued at claim (IAT)

### ISSUE THREAD

**Issue by thomaswoeckinger** [smallrye/smallrye-jwt#503]
Issued AT is optional for JWT as described in https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6.

The DefaultJWTTokenParser assigns the variable issuedAtRequired in line 121 by:

```
            final boolean issuedAtRequired = authContextInfo.getMaxTimeToLiveSecs() == null
                    || authContextInfo.getMaxTimeToLiveSecs() > 0;
```

which should be:

```
            final boolean issuedAtRequired = authContextInfo.getMaxTimeToLiveSecs() != null
                    && authContextInfo.getMaxTimeToLiveSecs() > 0;
```

**Comment by sberyozkin** [comment]
@thomaswoeckinger Hi, thanks for opening the issue. I'm afraid it is an invalid issue. `MP JWT` != `JWT`. JWT is a base spec, everything is optional there, one could equally say then the bug is that an expiry claim is also enforced. MP JWT enforces that an issued token has an expiry and issued at claims.  Any good OIDC provider would set an issued at claim. There is no technical reason why a self-issuing provider can't do either. 
We would not like to support the tokens which may never expire and at least by default we'd like to avoid supporting the tokens which may have been around for a year. 
If you are dealing with a legacy case then please set `smallrye.jwt.time-to-live=-1`

https://smallrye.io/docs/smallrye-jwt/configuration.html
